var inputImageSource = "example.jpg";

var inputResImageSourceList = [
    //0
    "res/rise_map.png",
    "res/yingcai_map.png",
    "res/blank.png",
    "res/blank.png",
    "res/blank.png",
    //1
    "res/map_1977.png",
    "res/blank.png",
    "res/blank.png",
    "res/blank.png",
    "res/blank.png",
    //2
    "res/blackboard_1024.png",
    "res/overlay_map.png",
    "res/amaro_map.png",
    "res/blank.png",
    "res/blank.png",
    //3
    "res/brannan_process.png",
    "res/brannan_blowout.png",
    "res/brannan_contrast.png",
    "res/brannan_luma.png",
    "res/brannan_screen.png",
    //4
    "res/earlybird_curves.png",
    "res/earlybird_overlay_map.png",
    "res/vignette_map.png",
    "res/earlybird_blowout.png",
    "res/earlybird_map.png",
    //5
    "res/edge_burn.png",
    "res/hefe_map.png",
    "res/hefe_gradient_map.png",
    "res/hefe_soft_light.png",
    "res/hefe_metal.png",
    //6
    "res/hudson_background.png",
    "res/overlay_map.png",
    "res/hudson_map.png",
    "res/blank.png",
    "res/blank.png",
    //7
    "res/inkwell_map.png",
    "res/blank.png",
    "res/blank.png",
    "res/blank.png",
    "res/blank.png",
    //8
    "res/lomo_map.png",
    "res/vignette_map.png",
    "res/blank.png",
    "res/blank.png",
    "res/blank.png",
    //9
    "res/kelvin_map.png",
    "res/blank.png",
    "res/blank.png",
    "res/blank.png",
    "res/blank.png",
    //10
    "res/nashville_map.png",
    "res/blank.png",
    "res/blank.png",
    "res/blank.png",
    "res/blank.png",
    //11
    "res/blackboard_1024.png",
    "res/overlay_map.png",
    "res/rise_map.png",
    "res/blank.png",
    "res/blank.png",
    //12
    "res/sierra_vignette.png",
    "res/overlay_map.png",
    "res/sierra_map.png",
    "res/blank.png",
    "res/blank.png",
    //13
    "res/vignette_map.png",
    "res/sutro_metal.png",
    "res/soft_light.png",
    "res/sutro_edge_burn.png",
    "res/sutro_curves.png",
    //14
    "res/toaster_metal.png",
    "res/toaster_soft_light.png",
    "res/toaster_curves.png",
    "res/toaster_overlay_map_warm.png",
    "res/toaster_color_shift.png",
    //15
    "res/valencia_map.png",
    "res/valencia_gradient_map.png",
    "res/blank.png",
    "res/blank.png",
    "res/blank.png",
    //16
    "res/walden_map.png",
    "res/vignette_map.png",
    "res/blank.png",
    "res/blank.png",
    "res/blank.png",
    //17
    "res/xpro_map.png",
    "res/vignette_map.png",
    "res/blank.png",
    "res/blank.png",
    "res/blank.png"
];
